import { createAnalyticsTools } from "./analytics-tools.js";
import { createBackupTools } from "./backup-tools.js";
import { createCoreTools } from "./direct-tools.js";
import { createMutationTools } from "./mutation-tools.js";
import { createProfileImpactTools } from "./profile-impact-tools.js";
import { createSimulationAndReportTools } from "./simulation-report-tools.js";
import type { ToolDefinition } from "./types.js";

export function createTools(): ToolDefinition[] {
  const tools = [
    ...createCoreTools(),
    ...createAnalyticsTools(),
    ...createSimulationAndReportTools(),
    ...createProfileImpactTools(),
    ...createBackupTools(),
    ...createMutationTools()
  ];

  const names = new Set<string>();
  for (const tool of tools) {
    if (names.has(tool.name)) {
      throw new Error(`Duplicate tool name: ${tool.name}`);
    }
    names.add(tool.name);
  }

  return tools;
}

export const expectedToolNames = [
  "health_check_all",
  "get_system_status",
  "get_app_config",
  "test_connection",
  "get_api_version",
  "get_quality_profiles",
  "get_quality_profile",
  "get_quality_definitions",
  "get_custom_formats",
  "get_language_profiles",
  "get_delay_profiles",
  "get_tags",
  "get_root_folders",
  "get_download_clients",
  "get_indexers",
  "get_notifications",
  "get_metadata_profiles",
  "get_naming_config",
  "get_media_management_config",
  "get_disk_space",
  "get_health",
  "radarr_get_movies",
  "radarr_get_movie",
  "radarr_get_movie_files",
  "radarr_get_missing",
  "radarr_get_cutoff_unmet",
  "sonarr_get_series",
  "sonarr_get_episodes",
  "sonarr_get_episode_files",
  "sonarr_get_missing",
  "sonarr_get_cutoff_unmet",
  "get_history",
  "get_grab_history",
  "get_import_history",
  "get_failed_history",
  "get_deleted_history",
  "get_queue",
  "get_queue_details",
  "get_blocklist",
  "get_indexer",
  "get_indexer_status",
  "get_indexer_stats",
  "get_indexer_history",
  "test_indexer",
  "test_all_indexers",
  "get_applications",
  "library_summary",
  "library_storage_stats",
  "library_codec_distribution",
  "library_resolution_distribution",
  "library_hdr_distribution",
  "library_audio_distribution",
  "library_quality_distribution",
  "library_profile_usage",
  "library_growth_statistics",
  "quality_profile_usage",
  "quality_distribution",
  "codec_distribution",
  "resolution_distribution",
  "hdr_distribution",
  "audio_distribution",
  "cutoff_unmet_by_profile",
  "upgrade_candidates",
  "profile_overlap",
  "redundant_quality_profiles",
  "custom_format_hits",
  "custom_format_misses",
  "unused_custom_formats",
  "duplicate_custom_formats",
  "conflicting_custom_formats",
  "storage_usage",
  "storage_by_codec",
  "storage_by_quality",
  "storage_by_resolution",
  "storage_growth",
  "estimated_storage_savings",
  "download_volume_by_indexer",
  "grabs_by_indexer",
  "imports_by_indexer",
  "failed_downloads_by_indexer",
  "success_rate_by_indexer",
  "average_release_size",
  "quality_by_indexer",
  "codec_by_indexer",
  "language_by_indexer",
  "release_group_by_indexer",
  "duplicate_grabs",
  "wasted_downloads",
  "simulate_quality_profile_change",
  "simulate_custom_format_change",
  "simulate_cutoff_change",
  "simulate_score_change",
  "simulate_storage_savings",
  "simulate_storage_growth",
  "simulate_upgrade_impact",
  "simulate_codec_strategy",
  "simulate_profile_impact",
  "create_backup",
  "list_backups",
  "restore_backup",
  "generate_diff",
  "validate_patch",
  "dry_run_patch",
  "apply_patch",
  "update_quality_profile",
  "create_quality_profile",
  "clone_quality_profile",
  "delete_quality_profile",
  "update_custom_format",
  "update_custom_format_score",
  "bulk_update_scores",
  "update_quality_definition",
  "update_delay_profile",
  "update_naming",
  "update_media_management",
  "update_restrictions",
  "report_quality_review",
  "report_storage_review",
  "report_tracker_review",
  "report_failed_downloads",
  "report_monthly_statistics",
  "report_recommendations",
  "continue_query"
] as const;
